/*
 * File: app/store/StTreeSprav.js
 * Date: Tue Mar 14 2017 13:43:49 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.store.StTreeSprav', {
    extend: 'Ext.data.TreeStore',
    alias: 'store.stTreeSprav',

    requires: [
        'Bank.model.MdTreeSprav',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'stTreeSprav',
            model: 'Bank.model.MdTreeSprav',
            root: {
                expanded: true,
                children: [
                    {
                        id: 'YisKassa',
                        text: 'Реестры платежей',
                        expanded: true,
                        children: [
                            {
                                id: 'KassirReestrDay',
                                leaf: true,
                                text: 'Реестр по адресам'
                            },
                            {
                                id: 'KassaReestr',
                                leaf: true,
                                text: 'Реестр по кассе'
                            },
                            {
                                id: 'KassaReestrOsmd',
                                leaf: true,
                                text: 'Реестр кассы по ОСМД'
                            },
                            {
                                id: 'OtdelReestr',
                                leaf: true,
                                text: 'Свод по отделениям'
                            },
                            {
                                id: 'BankReestr',
                                leaf: true,
                                text: 'Реестр по банку'
                            },
                            {
                                id: 'BankReestrOsmd',
                                leaf: true,
                                text: 'Реестр банка ОСМД'
                            },
                            {
                                id: 'BankControl',
                                leaf: true,
                                text: 'Контроль платежей'
                            }
                        ]
                    }
                ]
            },
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});