/*
 * File: app/store/StUsluga.js
 * Date: Thu Dec 03 2020 20:04:37 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.store.StUsluga', {
    extend: 'Ext.data.Store',
    alias: 'store.stUsluga',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array',
        'Ext.data.field.String'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'stUsluga',
            data: [
                {
                    usluga: 'Квартплата'
                },
                {
                    usluga: 'Опалення та ПТН'
                },
                {
                    usluga: 'Водопостачання та водовідведення'
                },
                {
                    usluga: 'Вивiз та зоховання ТПО'
                },
                {
                    usluga: 'Інформаційні послуги'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'array'
                }
            },
            fields: [
                {
                    type: 'string',
                    name: 'usluga'
                }
            ]
        }, cfg)]);
    }
});