/*
 * File: app/model/MdLoginLocal.js
 * Date: Wed May 27 2015 14:30:44 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.model.MdLoginLocal', {
    extend: 'Ext.data.Model',
    alias: 'model.mdLoginLocal',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'user_id'
        },
        {
            type: 'string',
            name: 'login'
        },
        {
            type: 'string',
            name: 'firstname'
        },
        {
            type: 'string',
            name: 'lastname'
        },
        {
            type: 'string',
            name: 'surname'
        },
        {
            type: 'int',
            name: 'otdel_id'
        },
        {
            type: 'int',
            name: 'role',
            persist: false
        },
        {
            type: 'int',
            name: 'remember'
        },
        {
            type: 'string',
            name: 'tbank'
        },
        {
            type: 'string',
            name: 'password'
        }
    ]
});