/*
 * File: app/model/MdOplata.js
 * Date: Fri May 29 2020 15:10:47 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.model.MdOplata', {
    extend: 'Ext.data.Model',
    alias: 'model.mdOPlata',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            name: 'address_id'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'int',
            name: 'god'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'float',
            name: 'kvartplata'
        },
        {
            type: 'float',
            name: 'otoplenie'
        },
        {
            type: 'float',
            name: 'ptn'
        },
        {
            type: 'float',
            name: 'podogrev'
        },
        {
            type: 'float',
            name: 'voda'
        },
        {
            type: 'float',
            name: 'stoki'
        },
        {
            type: 'float',
            name: 'tbo'
        },
        {
            type: 'float',
            name: 'summa'
        },
        {
            type: 'string',
            name: 'prixod'
        },
        {
            type: 'string',
            name: 'kassa'
        },
        {
            type: 'int',
            name: 'nomer'
        },
        {
            type: 'string',
            name: 'operator'
        },
        {
            type: 'date',
            name: 'data_in'
        },
        {
            name: 'chek'
        },
        {
            type: 'int',
            name: 'filial_id'
        },
        {
            type: 'int',
            name: 'orgl_id'
        },
        {
            type: 'string',
            name: 'filial'
        },
        {
            type: 'int',
            name: 'rec_id'
        },
        {
            type: 'string',
            name: 'pr'
        },
        {
            type: 'float',
            name: 'remont'
        }
    ]
});