/*
 * File: app/model/MdSvod.js
 * Date: Wed May 27 2015 14:23:59 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.model.MdSvod', {
    extend: 'Ext.data.Model',
    alias: 'model.mdSvod',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'nomer'
        },
        {
            type: 'string',
            name: 'type'
        },
        {
            type: 'string',
            name: 'data'
        },
        {
            type: 'string',
            name: 'bank_payer'
        },
        {
            type: 'string',
            name: 'mfo_payer'
        },
        {
            type: 'string',
            name: 'okpo_payer'
        },
        {
            type: 'string',
            name: 'acc_payer'
        },
        {
            type: 'string',
            name: 'bank_receiv'
        },
        {
            type: 'string',
            name: 'mfo_receiv'
        },
        {
            type: 'string',
            name: 'okpo_receiv'
        },
        {
            type: 'string',
            name: 'acc_receiv'
        },
        {
            type: 'string',
            name: 'summa'
        },
        {
            type: 'string',
            name: 'detali'
        },
        {
            type: 'string',
            name: 'symbol_pay'
        },
        {
            type: 'string',
            name: 'client'
        }
    ]
});