/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'MdLgotnik',
        'MdHouses',
        'MdOplata',
        'MdBank',
        'MdSvod',
        'MdUser',
        'MdStreet',
        'MdTekNachKassa',
        'MdLoginLocal',
        'MdAddress',
        'MdPriborUcheta',
        'MdAppartment',
        'MdLogin',
        'MdRaion',
        'MdTreeSprav'
    ],
    stores: [
        'StLoginLocal',
        'StHouses',
        'StTreeSprav',
        'StOtdelenieBank',
        'StOplata',
        'StOperatorBank',
        'StReestr',
        'StReport',
        'StLgotnik',
        'StStreet',
        'StTekPokVodomera',
        'StUsluga',
        'StRole',
        'StSvod',
        'StUser',
        'StCbOtdelenieBank',
        'StAddress',
        'StVodomerKassa',
        'StLogin',
        'StRaion',
        'StWater',
        'StTekOplata',
        'StPriznak',
        'StTekNachKassa',
        'StAppartment',
        'StClientBanka',
        'StCbOperatorBank'
    ],
    views: [
        'sprav.TabReportOrg',
        'NField',
        'sprav.WinUploadFile',
        'sprav.TabClientbanka',
        'NFieldVodomer',
        'flat.TabKassa',
        'sprav.TabOtdelenie',
        'menu.TabPnLeft',
        'VpKommuna',
        'sprav.TabSvod',
        'sprav.TabReestr',
        'sprav.WinOtdelenie',
        'sprav.WinClientBanka',
        'sprav.WinReport',
        'sprav.TabOperator',
        'sprav.WinOperator',
        'sprav.TabLogin',
        'user.WinLogin',
        'user.FmLogin',
        'menu.TabPnCenter'
    ],
    controllers: [
        'Admin',
        'CrKassa',
        'CrLeftMenu',
        'CrLogin',
        'crOtchet'
    ],
    name: 'Bank',

    launch: function() {
        Ext.create('Bank.view.VpKommuna');

        //закрываем значок загрузка...
        var loading =Ext.get('loading');
        if(loading){
            setTimeout(function(){

                loading.remove();
                Ext.get('loading-mask').fadeOut({remove:true});
            }, 250);
        }
    }

});
