/*
 * File: app/view/user/WinLogin.js
 * Date: Fri May 29 2020 12:01:51 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.user.WinLogin', {
    extend: 'Ext.window.Window',
    alias: 'widget.winlogin',

    requires: [
        'Bank.view.user.WinLoginViewModel',
        'Bank.view.user.FmLogin',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'winLogin'
    },
    height: 346,
    id: 'winLogin',
    width: 657,
    layout: 'fit',
    closable: false,
    title: 'Авторизация',
    modal: true,

    items: [
        {
            xtype: 'fmlogin',
            height: 312,
            style: 'background-color: #DCDCDC;'
        }
    ]

});