/*
 * File: app/controller/CrLogin.js
 * Date: Thu May 28 2015 00:10:00 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.controller.CrLogin', {
    extend: 'Ext.app.Controller',
    alias: 'controller.crLogin',

    models: [
        'MdLogin',
        'MdUser',
        'MdStreet',
        'MdRaion',
        'MdHouses'
    ],
    stores: [
        'StLogin',
        'StUser',
        'StStreet',
        'StRaion',
        'StHouses',
        'StCbOtdelenieBank',
        'StCbOperatorBank'
    ],
    views: [
        'VpKommuna',
        'user.WinLogin',
        'menu.TabPnCenter'
    ],

    refs: {
        WinLogin: {
            autoCreate: true,
            forceCreate: true,
            selector: '#winLogin',
            xtype: 'winlogin'
        },
        VpKommuna: '#vpKommuna',
        Vplogin: {
            selector: '#vpLogin',
            xtype: 'vplogin'
        },
        CbStreet: '#cbStreet',
        CbRaion: '#cbRaion',
        tabPnCenter: {
            selector: '#tabPnCenter',
            xtype: 'tabpncenter'
        },
        FmLogin: {
            selector: '#fmLogin',
            xtype: 'fmlogin'
        }
    },

    control: {
        "#btninput": {
            click: 'onBtninputClick'
        }
    },

    onBtninputClick: function(button, e, eOpts) {
        // in use
        var me = this;
        //WIN
        var win = Ext.getCmp('winLogin');

        //var WinLogin = me.getWinLogin();
        //STORE
        var stUser = me.getStUserStore();
        var storeRaion = me.getStRaionStore();
        var storeStreet = me.getStStreetStore();
        // ALL STORES

        var storeLocal = Ext.data.StoreManager.get("StLoginLocal");

        //FORM
        var chekLogin = Ext.getCmp('chekLogin');

        var form = me.getFmLogin();
        var values = form.getValues();
        var attempt = 0;
        //LOGIKA

        attempt += parseInt(values.attempt,10)+1 ;
        QueryUserLogin.login(values,function(results){
            if (results.success===true){
                //console.log(results);
                stUser.add({'login':results.login,'user_id':results.user_id,
                'password':results.password,'role':results.role,'otdel_id':values.otdel_id,'tbank':results.bank});
                stUser.sync();

                if((values.remember)){
                    // проверяем нужно ли сохранять его в локальном хранилище, если да(remember=1)
                    // получаем обьект локального хранилища StUserLocal и добавляем в него пользователя
                    // после чего показываем окно завершения регистрации
                    storeLocal.load();
                    storeLocal.removeAll();
                    storeLocal.sync();
                    storeLocal.add({tbank:results.bank,otdel_id:values.otdel_id,user_id:results.user_id,login:results.login,password:results.password,role:results.role,remember:1});
                    storeLocal.sync();

                }

                // ЛЕВОЕ МЕНЮ (ЖФ)
                storeRaion.load({
                    params: {
                        what:'raion'
                    },
                    scope: this
                });
                storeStreet.load({
                    params: {
                        what:'street'

                    },
                    scope: this
                });

                win.close();

            } else {
                if (attempt>5){

                    Ext.MessageBox.show({
                        title: 'Авторизация',
                        msg: '<center>Вы исчерпали количество попыток !!! <br> Логин или пароль неверный, <br> До свидания !!!</center>',
                        buttons: null,
                        icon: Ext.MessageBox.ERROR
                    });
                    setTimeout(function(){
                        location.href = "http://ya.ru";

                    }, 5000);
                }
                form.getForm().findField('attempt').setValue(attempt);
                chekLogin.setText('Логин или пароль неверный. Попытка № '+attempt).show();
            }
        });

    },

    onLaunch: function() {
        //in use
        var me=this;
        //TAB
        //console.log('tab');
        var stCbOperatorBank =  me.getStCbOperatorBankStore();

        var stCbOtdelenieBank = me.getStCbOtdelenieBankStore();

        stCbOperatorBank.load({
            params: {
                what:'OperatorBanka'
            }
        });
        stCbOtdelenieBank.load({
            params: {
                what:'OtdelenieBanka'
            }
        });

        var tabPnCenter = me.getTabPnCenter();
        //console.log(tabPnCenter);


        /*
        COMPONENT
        */
        //КВАРТИРЫ
        tabPnCenter.child('#tabKassa').tab.hide();


        //СПРАВОЧНИК
        tabPnCenter.child('#tabLogin').tab.hide();

        var WinLogin = me.getWinLogin();
        WinLogin.show();



        var fmLogin =  me.getFmLogin().getForm();
        var info_remember = Ext.getCmp('info_remember');
        var values = fmLogin.getValues();
        //console.log(values);

        //получаем обьект локального хранилища
        var storeLocal = Ext.data.StoreManager.get("StLoginLocal");
        //получаем обьект хранилища в котором будут находиться  данные о пользователе
        // загружаем сохраненные данные на машине пользователя в локальное хранилище
        storeLocal.load();

        if(storeLocal.data.length){
            var otdel_id = storeLocal.last().get('otdel_id');
            var login = storeLocal.last().get('login');
            var user_id = storeLocal.last().get('user_id');
            var passwd = storeLocal.last().get('password');
            //   fmLogin.findField('kod').setValue(kod);
            //   fmLogin.findField('login').setValue(user_id);


            if(Ext.isEmpty(login)){
                //Проверяем локальное хранилище
                //Если есть сохраненные данные,то
                //находим последнюю запись и получаем ид пользователя и пароль;

            } else {
                fmLogin.findField('otdel_id').setValue(otdel_id);
                fmLogin.findField('user_id').setValue(user_id);
                fmLogin.findField('password').setValue(passwd);
            }
        }

    }

});
