/*
 * File: app/view/sprav/TabOtdelenie.js
 * Date: Thu May 28 2015 10:26:38 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.sprav.TabOtdelenie', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabotdelenie',

    requires: [
        'Bank.view.sprav.TabOtdelenieViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action'
    ],

    viewModel: {
        type: 'tabOtdelenie'
    },
    id: 'tabOtdelenie',
    scrollable: true,
    layout: 'fit',
    title: 'Отделения',

    items: [
        {
            xtype: 'gridpanel',
            id: 'grOtdelenie',
            scrollable: true,
            width: 522,
            title: 'Ввод и редактированние списка отделений банка',
            store: 'StOtdelenieBank',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    height: 43,
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var stUser = Ext.data.StoreManager.get("StUser");
                                var values =stUser.getAt(0);
                                //LOGIKA'
                                values.set({'vibor':'addOtdelenie'});
                                stUser.sync();
                                var winOtdelenie = Ext.ClassManager.instantiateByAlias('widget.winotdelenie');
                                var form = winOtdelenie.down('#fmOtdelenie');
                                form.getForm().findField('newid').hide();

                                winOtdelenie.show();
                            },
                            id: 'btnAddOtdelenie',
                            icon: 'resources/css/images/ico/add.png',
                            text: 'Добавить отделение'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    width: 54,
                    dataIndex: 'otdel_id',
                    menuDisabled: true,
                    text: 'Ид',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    width: 118,
                    dataIndex: 'otdel',
                    menuDisabled: true,
                    text: 'Отделение'
                },
                {
                    xtype: 'gridcolumn',
                    width: 250,
                    dataIndex: 'address',
                    menuDisabled: true,
                    text: 'Адрес'
                },
                {
                    xtype: 'numbercolumn',
                    width: 130,
                    dataIndex: 'account',
                    menuDisabled: true,
                    text: 'Счет',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    width: 130,
                    dataIndex: 'taccount',
                    menuDisabled: true,
                    text: 'Тсчет',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    width: 66,
                    dataIndex: 'timeout',
                    menuDisabled: true,
                    text: 'Дн/Веч',
                    format: '0'
                },
                {
                    xtype: 'actioncolumn',
                    width: 39,
                    menuDisabled: true,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                Ext.MessageBox.confirm({
                                    title: 'Обновление данных ',
                                    msg: 'Вы обновляете данные оператора. <br>Подтвердите или отмените свои действия.',
                                    buttons: Ext.MessageBox.OKCANCEL,
                                    icon: Ext.MessageBox.ERROR,
                                    buttonText:{
                                        ok:'подтвеждаю',
                                        cancel:'отмена'
                                    },
                                    fn:function(btn,newValue){
                                        if(btn=='ok'){
                                            var winOtdelenie = Ext.ClassManager.instantiateByAlias('widget.winotdelenie');
                                            var form = winOtdelenie.down('#fmOtdelenie');
                                            var otdel_id = form.getForm().findField('otdel_id').getValue();

                                            var stUser = Ext.data.StoreManager.get("StUser");
                                            var values =stUser.getAt(0);
                                            values.set({'vibor':'editOtdelenie'});
                                            stUser.sync();
                                            var value = record;

                                            view.getSelectionModel().select(rowIndex);
                                            form.loadRecord(value);
                                            form.down('#btAddOtdelenie').setText('Обновмть данные');
                                            form.getForm().findField('newid').setValue(value.get('otdel_id'));
                                            winOtdelenie.setTitle('Редактирование записи');
                                            winOtdelenie.show();
                                        }
                                    }
                                });

                            },
                            icon: 'resources/css/images/ico/edit.png'
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    width: 34,
                    menuDisabled: true,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var grid = view.findParentByType('grid');
                                var store = view.store;
                                var stUser = Ext.data.StoreManager.get("StUser");
                                var values =stUser.getAt(0);
                                var tbank = values.get('tbank');
                                var params = {
                                    tbank:values.get('tbank'),
                                    what:"deleteOtdelenie"
                                };
                                var value = view.getStore().getAt(rowIndex).data;
                                //LOGIKA
                                Ext.Object.merge(value, params);
                                Ext.MessageBox.show({
                                    title: 'Внимание!',
                                    msg: 'Вы удаляете запись ! Подтвердите свои действия!',
                                    buttons: Ext.MessageBox.OKCANCEL,
                                    icon: Ext.MessageBox.WARNING,

                                    buttonText:{
                                        ok: "Удалить!",
                                        cancel: "Отмена"
                                    },
                                    fn:function(btn){
                                        if(btn=='ok'){
                                            QuerySprav.destroyRecord(value,function(results){
                                                if (results.success){
                                                    Ext.MessageBox.show({
                                                        title: 'Удаление записи',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.INFO
                                                    });
                                                    store.load({
                                                        params:{
                                                            what:'getOtdelenie',
                                                            tbank: tbank

                                                        },
                                                        scope:this
                                                    });
                                                } else {
                                                    Ext.MessageBox.show({
                                                        title: 'Удаление записи',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.ERROR
                                                    });
                                                }
                                            });
                                        }
                                    }
                                });
                            },
                            icon: 'resources/css/images/ico/no.png'
                        }
                    ]
                }
            ]
        }
    ]

});