/*
 * File: app/view/sprav/TabReestrViewController.js
 * Date: Thu May 28 2015 22:57:23 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.sprav.TabReestrViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tabReestr',

    onCellEditingEdit: function(editor, context, eOpts) {

        var stUser = Ext.data.StoreManager.get("StUser");

        var values =stUser.getAt(0);
        var tbank = values.get('tbank');
        var address_id = values.get('address_id');

        var params =
        {'what':'getReestr',
            'tbank':tbank
        };
        //console.log(context.record);

        var value = context.record.data;
        Ext.Object.merge(value, params);
        var store = editor.grid.store;

        //LOGIN & PASSWORD



        QuerySprav.updateRecords(value,function(results){
            console.log(results);


            if (results.success){
                store.load({
                    params: {
                        what:'getReestr',
                        address_id: address_id ,
                        tbank: tbank
                    },
                    scope:this
                });
            }else{
                store.load({
                    params: {
                        what:'getReestr',
                        address_id: address_id ,
                        tbank: tbank
                    },
                    scope:this
                });
            }
        });
    }

});
