/*
 * File: app/view/sprav/TabSvod.js
 * Date: Thu May 28 2015 23:05:52 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.sprav.TabSvod', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabsvod',

    requires: [
        'Bank.view.sprav.TabSvodViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.feature.GroupingSummary',
        'Ext.grid.column.Number',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'tabSvod'
    },
    id: 'tabSvod',
    scrollable: true,
    layout: 'fit',
    title: 'Свод',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'grSvod',
            scrollable: true,
            width: 522,
            title: 'Свод принятой оплаты из реестра платежей',
            forceFit: false,
            store: 'StSvod',
            features: [
                {
                    ftype: 'groupingsummary'
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 34,
                    dataIndex: 'id',
                    menuDisabled: true,
                    text: 'ид',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    width: 59,
                    align: 'center',
                    dataIndex: 'nomer',
                    menuDisabled: true,
                    text: '№<br> док'
                },
                {
                    xtype: 'gridcolumn',
                    width: 43,
                    dataIndex: 'type',
                    menuDisabled: true,
                    text: 'Тип'
                },
                {
                    xtype: 'gridcolumn',
                    width: 85,
                    dataIndex: 'data',
                    menuDisabled: true,
                    text: 'Дата'
                },
                {
                    xtype: 'gridcolumn',
                    width: 104,
                    align: 'right',
                    dataIndex: 'summa',
                    menuDisabled: true,
                    text: 'Сумма'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.String.format('<div class="topic"> <b>{0}</b><span class="author">МФО {1} </span><span class="author">ЕДРПУ {2}</span><br><span class="author">р.сч {3} </span></div>',
                        value,record.get('mfo_payer') || "",record.get('okpo_payer') || "",record.get('acc_payer') || "");
                    },
                    width: 223,
                    dataIndex: 'bank_payer',
                    menuDisabled: true,
                    text: 'Плательщик'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 62,
                    dataIndex: 'mfo_payer',
                    menuDisabled: true,
                    text: 'МФО'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 60,
                    dataIndex: 'okpo_payer',
                    menuDisabled: true,
                    text: 'ЕДРПУ'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'acc_payer',
                    menuDisabled: true,
                    text: 'Счет'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.String.format('<div class="topic"> <b>{0}</b><span class="author"> {1} </span><span class="author"> {2}</span><br><span class="author">р.сч {3} </span><span class="author">едрпу {4} </span></div>',
                        value,record.get('bank_receiv') || "",record.get('mfo_receiv') || "",record.get('acc_receiv') || "",record.get('okpo_receiv') || "");
                    },
                    width: 268,
                    dataIndex: 'client',
                    menuDisabled: true,
                    text: 'Получатель'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 179,
                    dataIndex: 'bank_receiv',
                    menuDisabled: true,
                    text: 'банк'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 48,
                    dataIndex: 'mfo_receiv',
                    menuDisabled: true,
                    text: 'МФО'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 64,
                    dataIndex: 'okpo_receiv',
                    menuDisabled: true,
                    text: 'ЕДРПУ'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'acc_receiv',
                    menuDisabled: true,
                    text: 'Счет'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.style = 'white-space:pre-wrap;';
                        return value;

                    },
                    width: 249,
                    dataIndex: 'detali',
                    menuDisabled: true,
                    text: 'Детали платежа'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'symbol_pay',
                    text: 'Symbol_pay'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'datefield',
                            id: 'dateSvod',
                            width: 158,
                            fieldLabel: 'Дата',
                            labelWidth: 40,
                            format: 'd-m-Y',
                            submitFormat: 'Ymd',
                            listeners: {
                                select: 'onDateSvodSelect'
                            }
                        },
                        {
                            xtype: 'combobox',
                            id: 'cbKassaSvod',
                            width: 145,
                            fieldLabel: 'касса',
                            labelWidth: 50,
                            displayField: 'kassa',
                            queryMode: 'local',
                            store: 'StPriznak',
                            valueField: 'pr',
                            listeners: {
                                select: 'onCbKassaSvodSelect'
                            }
                        },
                        {
                            xtype: 'combobox',
                            id: 'cbOtdelenieSvod',
                            width: 254,
                            fieldLabel: 'Отделение',
                            labelWidth: 80,
                            displayField: 'otdel',
                            queryMode: 'local',
                            store: 'StCbOtdelenieBank',
                            valueField: 'otdel_id',
                            listeners: {
                                select: 'onComboboxSelect'
                            }
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'printSvod',
                            icon: 'resources/css/images/ico/print_printer.png',
                            scale: 'large',
                            text: 'Печать',
                            tooltip: 'Печать свода'
                        },
                        {
                            xtype: 'tbspacer',
                            width: 50
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'exportSvod',
                            href: 'resources/php/csv/svod.php',
                            icon: 'resources/css/images/news/post_go.gif',
                            scale: 'medium',
                            text: 'Экспорт свода',
                            tooltip: 'Экспорт свода'
                        }
                    ]
                }
            ]
        }
    ],

    onDateSvodSelect: function(field, value, eOpts) {
        var otdel = Ext.getCmp('cbOtdelenieSvod');
        otdel.setValue("");
    },

    onCbKassaSvodSelect: function(combo, record, eOpts) {
        var otdel = Ext.getCmp('cbOtdelenieSvod');
        otdel.setValue("");
    },

    onComboboxSelect: function(combo, record, eOpts) {
        //in use

        //STORE
        var stUser = Ext.data.StoreManager.get("StUser");
        var StSvod = Ext.data.StoreManager.get("StSvod");
        var data = Ext.getCmp('dateSvod').getValue();
        var pr = Ext.getCmp('cbKassaSvod').getValue();
        var bt = Ext.getCmp('printSvod').setDisabled(false);
        var bt1 = Ext.getCmp('exportSvod').setDisabled(false);


        //LOGIN & PASSWORD

        var values =stUser.getAt(0);
        var tbank = values.get('tbank');
        var user_id = values.get('user_id');

        var params = {
            what:'getSvodOtdelenie',
            tbank: tbank,
            user_id: user_id,
            pr: pr,
            otdel_id: record.get('otdel_id'),
            data:data
        };
        //LOGIKA
        if (record) {

            QuerySprav.getProcedure(params,function(result){
                if(result.success==="1"){
                      StSvod.load({
                        params: {
                            what:'getSvodOtdelenie',
                            tbank: tbank,
                            user_id: user_id,
                            pr: pr,
                            otdel_id: record.get('otdel_id'),
                            data:data
                        },
                        scope:this
                    });


                } else {

                    Ext.MessageBox.show({title: 'Формирование свода',
                        msg: result.msg,
                        buttons: Ext.MessageBox.OK,
                        icon: Ext.MessageBox.ERROR
                    });
                }
            });
        }
    }

});