/*
 * File: app/view/sprav/WinClientBanka.js
 * Date: Thu Dec 03 2020 20:04:34 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.sprav.WinClientBanka', {
    extend: 'Ext.window.Window',
    alias: 'widget.winclientbanka',

    requires: [
        'Bank.view.sprav.WinClientBankaViewModel',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.field.Number',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'winClientBanka'
    },
    height: 544,
    id: 'winClientBanka',
    width: 611,
    layout: 'fit',
    title: 'Ввод нового клиента банка',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 441,
            id: 'fmClientBanka',
            style: 'background-color: #DCDCDC;',
            layout: 'absolute',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        button.up('#winClientBanka').close();
                    },
                    x: 35,
                    y: 440,
                    height: 30,
                    width: 80,
                    icon: 'resources/css/images/ico/delete.png',
                    text: 'Отмена'
                },
                {
                    xtype: 'fieldset',
                    x: 30,
                    y: 25,
                    height: 385,
                    style: 'background-color: #DCDCDC;',
                    width: 540,
                    layout: 'absolute',
                    title: 'Данные по клиенту',
                    items: [
                        {
                            xtype: 'combobox',
                            x: 0,
                            y: 10,
                            width: 515,
                            fieldLabel: 'Предоставляемые услуги клиентом',
                            labelWidth: 250,
                            name: 'usluga',
                            allowBlank: false,
                            displayField: 'usluga',
                            queryMode: 'local',
                            store: 'StUsluga',
                            valueField: 'usluga'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 55,
                            formBind: false,
                            width: 515,
                            fieldLabel: 'клиент',
                            labelWidth: 70,
                            name: 'client',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 95,
                            formBind: false,
                            width: 515,
                            fieldLabel: 'банк',
                            labelWidth: 70,
                            name: 'bank',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения'
                        },
                        {
                            xtype: 'textfield',
                            x: -2,
                            y: 220,
                            formBind: false,
                            width: 515,
                            fieldLabel: 'Счет',
                            labelWidth: 70,
                            name: 'account',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения'
                        },
                        {
                            xtype: 'textareafield',
                            x: 0,
                            y: 140,
                            height: 58,
                            width: 515,
                            fieldLabel: 'Адрес банка',
                            labelWidth: 70,
                            name: 'address'
                        },
                        {
                            xtype: 'textareafield',
                            x: 0,
                            y: 300,
                            height: 58,
                            width: 515,
                            fieldLabel: 'Детали платежа',
                            labelWidth: 70,
                            name: 'detali',
                            allowBlank: false
                        },
                        {
                            xtype: 'numberfield',
                            x: 30,
                            y: 265,
                            width: 150,
                            fieldLabel: 'МФО',
                            labelWidth: 40,
                            name: 'mfo',
                            allowBlank: false,
                            hideTrigger: true,
                            decimalPrecision: 0
                        },
                        {
                            xtype: 'numberfield',
                            x: 255,
                            y: 265,
                            width: 190,
                            fieldLabel: 'ЕДРПУ',
                            labelWidth: 60,
                            name: 'okpo',
                            allowBlank: false,
                            hideTrigger: true,
                            decimalPrecision: 0
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'client_id'
                },
                {
                    xtype: 'button',
                    x: 320,
                    y: 440,
                    formBind: true,
                    height: 30,
                    id: 'btAddClientBanka',
                    width: 250,
                    icon: 'resources/css/images/ico/add.png',
                    text: 'Добавить клиента'
                }
            ]
        }
    ]

});