/*
 * File: app/view/sprav/WinOtdelenie.js
 * Date: Fri May 29 2020 11:48:24 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.sprav.WinOtdelenie', {
    extend: 'Ext.window.Window',
    alias: 'widget.winotdelenie',

    requires: [
        'Bank.view.sprav.WinOtdelenieViewModel',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'winOtdelenie'
    },
    height: 476,
    id: 'winOtdelenie',
    width: 562,
    layout: 'fit',
    title: 'Ввод нового оператора',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 441,
            id: 'fmOtdelenie',
            layout: 'absolute',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'button',
                    x: 265,
                    y: 385,
                    formBind: true,
                    height: 30,
                    id: 'btAddOtdelenie',
                    width: 250,
                    icon: 'resources/css/images/ico/add.png',
                    text: 'Добавить отделение'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        button.up('#winOtdelenie').close();
                    },
                    x: 30,
                    y: 385,
                    height: 30,
                    width: 80,
                    icon: 'resources/css/images/ico/delete.png',
                    text: 'Отмена'
                },
                {
                    xtype: 'fieldset',
                    x: 30,
                    y: 25,
                    height: 330,
                    style: 'background-color: #DCDCDC;',
                    width: 485,
                    layout: 'absolute',
                    title: 'Данные по отделению',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 15,
                            formBind: false,
                            width: 360,
                            fieldLabel: 'Отделение',
                            labelWidth: 80,
                            name: 'otdel',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения'
                        },
                        {
                            xtype: 'numberfield',
                            x: 10,
                            y: 230,
                            formBind: false,
                            width: 210,
                            fieldLabel: 'Вечерняя касса (ччмм)',
                            labelWidth: 150,
                            name: 'timeout',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения',
                            hideTrigger: true,
                            maxLength: 4,
                            minLength: 4,
                            allowDecimals: false,
                            decimalPrecision: 0
                        },
                        {
                            xtype: 'numberfield',
                            x: 380,
                            y: 15,
                            formBind: false,
                            width: 80,
                            fieldLabel: 'ид',
                            labelWidth: 20,
                            name: 'newid',
                            blankText: 'Поле обязательное для заполнения',
                            hideTrigger: true,
                            allowDecimals: false,
                            decimalPrecision: 0
                        },
                        {
                            xtype: 'numberfield',
                            x: 10,
                            y: 180,
                            formBind: false,
                            width: 220,
                            fieldLabel: 'Счет',
                            labelWidth: 50,
                            name: 'account',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения',
                            hideTrigger: true,
                            allowDecimals: false,
                            decimalPrecision: 0
                        },
                        {
                            xtype: 'numberfield',
                            x: 240,
                            y: 180,
                            formBind: false,
                            width: 220,
                            fieldLabel: 'TСчет',
                            labelWidth: 50,
                            name: 'taccount',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения',
                            hideTrigger: true,
                            allowDecimals: false,
                            decimalPrecision: 0
                        },
                        {
                            xtype: 'textareafield',
                            x: 5,
                            y: 60,
                            width: 455,
                            fieldLabel: 'Адрес отделения',
                            labelAlign: 'top',
                            labelWidth: 70,
                            name: 'address'
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'otdel_id'
                }
            ]
        }
    ]

});