/*
 * File: app/view/sprav/WinReport.js
 * Date: Fri May 29 2020 12:11:50 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.sprav.WinReport', {
    extend: 'Ext.window.Window',
    alias: 'widget.winreport',

    requires: [
        'Bank.view.sprav.WinReportViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'winReport'
    },
    height: 285,
    id: 'winReport',
    width: 502,
    title: 'Выбор параметров',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            height: 441,
            id: 'fmWinReport',
            layout: 'fit',
            title: '',
            items: [
                {
                    xtype: 'fieldset',
                    style: 'background-color: #DCDCDC;',
                    layout: 'absolute',
                    title: '',
                    items: [
                        {
                            xtype: 'button',
                            x: 255,
                            y: 185,
                            formBind: true,
                            height: 30,
                            id: 'btnWinReport',
                            width: 170,
                            icon: 'resources/css/images/ico/add.png',
                            text: 'Сформировать'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var treeGrid = Ext.getCmp('treeMenuSpravView');
                                //var selectedItem = treeGrid.getSelectionModel().getSelection();
                                var model = treeGrid.getSelectionModel();
                                model.select(1);
                                this.up('#winReport').close();
                            },
                            x: 35,
                            y: 185,
                            height: 30,
                            width: 80,
                            icon: 'resources/css/images/ico/delete.png',
                            text: 'Отмена'
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 10,
                            height: 25,
                            id: 'headerReport',
                            style: '{color: #D15706; text-shadow: -1px -1px white, 1px 1px #333;font-size:14pt;}',
                            width: 420,
                            text: 'Наименование отчета'
                        },
                        {
                            xtype: 'fieldset',
                            x: 15,
                            y: 65,
                            height: 90,
                            id: 'fsGetPeriod',
                            maxWidth: 200,
                            style: 'background-color: #F1EEEE ;',
                            width: 170,
                            title: 'Период отчета',
                            items: [
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'dateRepFrom',
                                    fieldLabel: 'С',
                                    labelWidth: 20,
                                    name: 'date_from',
                                    format: 'd-m-Y',
                                    submitFormat: 'Y-m-d',
                                    listeners: {
                                        afterrender: 'onDateRepFromAfterRender',
                                        validitychange: 'onDateRepFromValidityChange'
                                    }
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'dateRepTo',
                                    itemId: 'dateRepTo',
                                    fieldLabel: 'По',
                                    labelWidth: 20,
                                    name: 'date_to',
                                    format: 'd-m-Y',
                                    submitFormat: 'Y-m-d',
                                    listeners: {
                                        afterrender: 'onDateRepToAfterRender'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            x: 205,
                            y: 65,
                            height: 90,
                            hidden: true,
                            id: 'fsVibor',
                            style: 'background-color: #F1EEEE ;',
                            width: 265,
                            title: 'Параметры выбора',
                            items: [
                                {
                                    xtype: 'combobox',
                                    hidden: true,
                                    id: 'cbOtdelenie',
                                    width: 225,
                                    fieldLabel: 'Отделение',
                                    labelWidth: 70,
                                    name: 'otdel_id',
                                    emptyText: 'Приход',
                                    displayField: 'otdel',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'StCbOtdelenieBank',
                                    typeAhead: true,
                                    valueField: 'otdel_id'
                                },
                                {
                                    xtype: 'combobox',
                                    hidden: true,
                                    id: 'cbPr',
                                    width: 225,
                                    fieldLabel: 'касса',
                                    labelWidth: 70,
                                    name: 'pr',
                                    value: [
                                        'D'
                                    ],
                                    emptyText: 'касса',
                                    displayField: 'kassa',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'StPriznak',
                                    typeAhead: true,
                                    valueField: 'pr'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onDateRepFromAfterRender: function(component, eOpts) {
        component.setValue(Ext.Date.getFirstDateOfMonth(new Date()) );
    },

    onDateRepFromValidityChange: function(field, isValid, eOpts) {
        if(isValid){
            var cb = Ext.getCmp('dateRepTo');
            cb.setValue(Ext.Date.getLastDateOfMonth(field.value));
        }
    },

    onDateRepToAfterRender: function(component, eOpts) {
        component.setValue(Ext.Date.getLastDateOfMonth(new Date()) );
    }

});