/*
 * File: app/view/sprav/WinUploadFile.js
 * Date: Fri May 29 2020 11:48:24 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.sprav.WinUploadFile', {
    extend: 'Ext.window.Window',
    alias: 'widget.winuploadfile',

    requires: [
        'Bank.view.sprav.WinUploadFileViewModel',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.File',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'winUploadFile'
    },
    height: 368,
    id: 'winUploadFile',
    width: 434,
    layout: 'fit',
    title: 'Ввод нового оператора',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 441,
            id: 'fmUploadFile',
            layout: 'absolute',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var form = button.findParentByType('form');
                        if(form.isValid()){
                            form.submit({
                                waitMsg:'Идет отправка...',
                                url: '/test_ajax.php',
                                params : {key : 'val', key2 : 'val2'},
                                success: function(form,response) {
                                    Ext.Msg.alert('Внимание','Успешно отправлено');
                                    console.log(response.result);
                                },
                                failure : function(){
                                    Ext.Msg.alert('Внимание','Какая то ошибка');
                                }
                            });
                        }else{
                            Ext.Msg.alert('Внимание','Заполните ВСЕ поля');
                        }
                    },
                    x: 210,
                    y: 260,
                    formBind: true,
                    height: 30,
                    id: 'btAddOperator1',
                    width: 185,
                    icon: 'resources/css/images/ico/add.png',
                    text: 'Загрузить файл'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        button.up('#winOperator').close();
                    },
                    x: 35,
                    y: 265,
                    height: 30,
                    width: 80,
                    icon: 'resources/css/images/ico/delete.png',
                    text: 'Отмена'
                },
                {
                    xtype: 'fieldset',
                    x: 30,
                    y: 25,
                    height: 215,
                    style: 'background-color: #DCDCDC;',
                    width: 365,
                    layout: 'absolute',
                    title: 'Файл для загрузки',
                    items: [
                        {
                            xtype: 'filefield',
                            x: 10,
                            y: 30,
                            width: 305,
                            fieldLabel: 'файл',
                            labelWidth: 50,
                            name: 'svodFile',
                            buttonText: 'Выбрать'
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'user_id'
                }
            ]
        }
    ]

});