/*
 * File: app/view/menu/TabPnCenter.js
 * Date: Fri May 29 2020 14:37:36 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bank.view.menu.TabPnCenter', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpncenter',

    requires: [
        'Bank.view.menu.TabPnCenterViewModel',
        'Bank.view.sprav.TabLogin',
        'Bank.view.flat.TabKassa',
        'Bank.view.sprav.TabOperator',
        'Bank.view.sprav.TabOtdelenie',
        'Bank.view.sprav.TabClientbanka',
        'Bank.view.sprav.TabReestr',
        'Bank.view.sprav.TabSvod',
        'Ext.panel.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'tabPnCenter'
    },
    border: false,
    id: 'tabPnCenter',
    activeTab: 0,
    plain: true,

    items: [
        {
            xtype: 'tablogin',
            title: 'Вход'
        },
        {
            xtype: 'tabkassa'
        },
        {
            xtype: 'taboperator'
        },
        {
            xtype: 'tabotdelenie'
        },
        {
            xtype: 'tabclientbanka'
        },
        {
            xtype: 'tabreestr'
        },
        {
            xtype: 'tabsvod'
        }
    ]

});